# Generated by Django 3.1.8 on 2021-05-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='diary.diary'),
        ),
    ]
