# Generated by Django 3.1.8 on 2021-05-10 11:37

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210510_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryimage',
            name='image',
            field=models.ImageField(null=True, upload_to=diary.models.diary_image_file_path),
        ),
    ]
